apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiQXNtYWVOZWRkYXkiLCJwYXNzd29yZCI6ImdocF9PQVBsUkxOZ0VEdE9xR3lFVlRKMXNza0x3TElMVUoycTFrWDIiLCJhdXRoIjoiUVhOdFlXVk9aV1JrWVhrNloyaHdYMDlCVUd4U1RFNW5SVVIwVDNGSGVVVldWRW94YzNOclRIZE1TVXhWU2pKeE1XdFlNZz09In19fQ==
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
